// This file contains types and methods for creating chat threads and entries
package chat

import "time"

// Type for chat thread, contains the two people involved and their conversation
type ChatThread struct {
	FirstPerson  string
	SecondPerson string
	Conversation []ChatEntry
}

// Type for a chat message, contains the sender, messsage, time, underlying system prompt and status
type ChatEntry struct {
	Sender       string
	Message      string
	Time         time.Time
	SystemPrompt string
	Status       string
}

// Method for creating a chat thread
func CreateChatThread(male string, female string) ChatThread {
	var conversation []ChatEntry
	return ChatThread{
		FirstPerson:  male,
		SecondPerson: female,
		Conversation: conversation,
	}
}

// Method for creating a chat message, returns the message generated by ChatGPT
func CreateChatMessage(user_prompt string, system_prompt string) string {
	var response ChatResponse = GenrateResponse(user_prompt, system_prompt)

	var replies []string = ParseRespone(response)

	return replies[0]
}

// Method for creating a chat entry for the generated message
func CreateChatEntry(sender string, user_prompt string, system_prompt string) ChatEntry {
	var message string = CreateChatMessage(user_prompt, system_prompt)

	return ChatEntry{
		Sender:       sender,
		Message:      message,
		Time:         time.Now(),
		SystemPrompt: system_prompt,
		Status:       "Sent",
	}
}
